---
ID: "0b2135c2-b08c-4dae-9b38-473a82f180b2"
Parent: "725dac3e-340f-4cf3-adad-3ceefa701cd1"
Template: "725dac3e-340f-4cf3-adad-3ceefa701cd1"
Path: /sitecore/templates/Project/GowlingWLG Site/Page Templates/Insights Landing/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {1C82E550-EBCD-4E5D-8ABD-D50D0809541E}
    {725DAC3E-340F-4CF3-ADAD-3CEEFA701CD1}
- ID: "4a749557-242b-4372-8a20-b2db9d406301"
  Hint: __AutoThumbnails
  Value: 
- ID: "d312103c-b36c-4ca5-864a-c85f9abda503"
  Hint: __Is Bucket
  Value: 1
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230627T124547Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\navya.mallepalli@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\navya.mallepalli@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "28c048ac-3534-436f-922b-6fc7fd7a282f"
    - ID: "b6e20f3d-c0a0-4a17-9d3b-c15ebc67d6d9"
      Hint: CategoryType
      Value: "{147DC2D6-02CF-42A8-A864-D7C3659F8D23}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\subham.agarwal@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231010T044752Z
