---
ID: "f7d52d0b-9eeb-4f28-bd0b-e93727ce006e"
Parent: "91b93b0e-e52d-45be-bc45-2e9d9c9f0856"
Template: "91b93b0e-e52d-45be-bc45-2e9d9c9f0856"
Path: /sitecore/templates/Project/GowlingWLG Site/Page Content/StatsWithCTA/StatsWithCTA/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{A758B4EB-EF0A-4752-A0AB-BA876FD886EC}"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230818T144123Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kumar.sumit@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kumar.sumit@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "314aff3a-084e-447d-a5f3-b453def5f893"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kumar.sumit@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230907T131009Z
