---
ID: "88768ae0-0f64-4ddc-8a85-e4735d09e55c"
Parent: "e334f407-b6af-4f25-85eb-95c3aeb3e148"
Template: "66a4442f-338d-493b-83a9-c1727e985320"
Path: /sitecore/content/GowlingWLG/GowlingWLG/Home/QA/Services/Product  Advertising
BranchID: "a4ab0efe-c950-4a31-a022-59f1e75c3596"
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{EA25391C-2E25-484B-8C7E-C42729774A91}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{95FC1954-3CCD-42D5-8A23-8622DA602ED5}"
          s:ds="{D295624A-BE6F-4FFD-B2B1-635A1562F4A2}"
          s:id="{354BD06E-2B25-4F09-8886-6210DE4B941A}"
          s:par="CSSStyles"
          s:ph="headless-main"
          s:ccb="Clear on publish" />
      </d>
    </r>
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{8DC5D0FD-E7AF-413E-B7E9-C3261812CBF5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{5E37E0C5-4200-470E-BD47-CCC7663AAD67}"
              p:after="r[@uid='{95FC1954-3CCD-42D5-8A23-8622DA602ED5}']"
              s:ds="local:/Data/HoverOverCards"
              s:id="{A9C60D1E-AF4C-4DB8-BE22-43338634CB38}"
              s:par="GridParameters&amp;CTABackgroundColor&amp;FieldNames=%7B81E71C31-2F34-400D-99AA-321BF3A06BA4%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main"
              s:ccb="Clear on publish" />
            <r
              uid="{D53B2200-FD1E-486B-8304-01B5C4D62584}"
              p:after="*[1=2]"
              s:ds="{1C51D4C2-4771-4083-91D9-F52C080AFBD3}"
              s:id="{70D77A7D-7805-44AB-9BF1-192AE57B6156}"
              s:par="CSSStyles"
              s:ph="headless-main"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230828T133541Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{06A113F8-7DAF-473F-BFAF-D0E534965E64}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product  Advertising
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sanjeevi.ram@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mahesh.kambhampati@altudo.co
    - ID: "77681060-f4b9-4504-b4e8-bf6e11d33601"
      Hint: Title
      Value: Product  Advertising
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bbafb8de-197d-454b-b2cf-a449eac55133"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kavya.bankapur@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230904T082641Z
