---
ID: "9d891ba0-d6f4-44ae-83b3-944384927799"
Parent: "77891984-7e21-45ff-a657-2203b78be33f"
Template: "77891984-7e21-45ff-a657-2203b78be33f"
Path: /sitecore/templates/Project/GowlingWLG Site/Page Templates/People Landing/__Standard Values
SharedFields:
- ID: "4a749557-242b-4372-8a20-b2db9d406301"
  Hint: __AutoThumbnails
  Value: 
- ID: "d312103c-b36c-4ca5-864a-c85f9abda503"
  Hint: __Is Bucket
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230719T154846Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sanjeevi.ram@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sanjeevi.ram@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8f634f80-61e6-44ab-ac17-3e0356cba04e"
    - ID: "b6e20f3d-c0a0-4a17-9d3b-c15ebc67d6d9"
      Hint: CategoryType
      Value: "{147DC2D6-02CF-42A8-A864-D7C3659F8D23}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanjeevi.ram@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230817T175255Z
