---
ID: "50dce73f-5010-4b56-bc63-659ebe6ace64"
Parent: "a0a28aa6-11ee-4dec-a76b-3e0f3ff28e0d"
Template: "a0a28aa6-11ee-4dec-a76b-3e0f3ff28e0d"
Path: /sitecore/templates/Project/GowlingWLG Site/Page Content/Bio Accordion/BioAccordionSelector/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {0A7AA373-5ED1-4E9B-9678-22D3C5FAF6DF}
    {0E773D3C-E2E3-457E-A3BB-24C8B1786B95}
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Value: 1
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Value: 1
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230627T152100Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sanjeevi.ram@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sanjeevi.ram@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "23934f05-77bd-4821-a3cd-42cfe814b2c7"
    - ID: "90d4ff5b-ce28-4a08-b204-570d399ec665"
      Hint: AccordionTitle
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanjeevi.ram@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230809T232523Z
