---
ID: "6eb07428-7c9a-4fd2-960d-2135dcb3a929"
Parent: "6831ed32-a917-408a-b7f1-201967800de0"
Template: "705a7160-d23c-454d-87ae-135d75534223"
Path: /sitecore/content/GowlingWLG/GowlingWLG/Home/Career/UK career/Students/Training contracts
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{9F6C845C-789A-4F33-A7D5-181798DC5202}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230928T081551Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Training contracts
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kavya.bankapur@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kavya.bankapur@altudo.co
    - ID: "77681060-f4b9-4504-b4e8-bf6e11d33601"
      Hint: Title
      Value: Training contracts
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dfe570af-10b4-4672-8bcb-553a9046722f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kavya.bankapur@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230928T081551Z
