const { fontFamily } = require('tailwindcss/defaultTheme');
const plugin = require('tailwindcss/plugin');
import { getPublicUrl } from '@sitecore-jss/sitecore-jss-nextjs/utils';
const publicUrl = getPublicUrl();

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-5',
    'col-span-6',
    'col-span-7',
    'col-span-8',
    'col-span-9',
    'col-span-10',
    'col-span-11',
    'col-span-12',
    'sm:col-span-1',
    'sm:col-span-2',
    'sm:col-span-3',
    'sm:col-span-4',
    'sm:col-span-5',
    'sm:col-span-6',
    'sm:col-span-7',
    'sm:col-span-8',
    'sm:col-span-9',
    'sm:col-span-10',
    'sm:col-span-11',
    'sm:col-span-12',
    'md:col-span-1',
    'md:col-span-2',
    'md:col-span-3',
    'md:col-span-4',
    'md:col-span-5',
    'md:col-span-6',
    'md:col-span-7',
    'md:col-span-8',
    'md:col-span-9',
    'md:col-span-10',
    'md:col-span-11',
    'md:col-span-12',
    'lg:col-span-1',
    'lg:col-span-2',
    'lg:col-span-3',
    'lg:col-span-4',
    'lg:col-span-5',
    'lg:col-span-6',
    'lg:col-span-7',
    'lg:col-span-8',
    'lg:col-span-9',
    'lg:col-span-10',
    'lg:col-span-11',
    'lg:col-span-12',
    'xl:col-span-1',
    'xl:col-span-2',
    'xl:col-span-3',
    'xl:col-span-4',
    'xl:col-span-5',
    'xl:col-span-6',
    'xl:col-span-7',
    'xl:col-span-8',
    'xl:col-span-9',
    'xl:col-span-10',
    'xl:col-span-11',
    'xl:col-span-12',
    '2xl:col-span-1',
    '2xl:col-span-2',
    '2xl:col-span-3',
    '2xl:col-span-4',
    '2xl:col-span-5',
    '2xl:col-span-6',
    '2xl:col-span-7',
    '2xl:col-span-8',
    '2xl:col-span-9',
    '2xl:col-span-10',
    '2xl:col-span-11',
    '2xl:col-span-12',
    'overflow-auto',
    'uppercase',
    'bg-purple',
    'bg-mainPurple',
    'bg-darkGrey',
    'bg-extraLightGrey',
    'bg-lightPurple',
    'mb-2.5',
    'mb-6',
    'mb-8',
    'mx-auto',
    'mx-0',
    'text-shadow-lg',
    'py-9.75',
    'border-t-[1px]',
    'md:border-t-0',
    'border-darkGrey',
    'border-solid',
    'lg:mx-0',
    'leading-normal',
    'md:text-[24px]',
    'md:float-right',
    'md:mb-[18px]',
    'h-fit',
    'min-h-[90vh]',
    'bg-darkBlue',
    'bg-lightBlue',
    'md:pt-6.5',
    'bg-mediumPurple',
  ],
  theme: {
    extend: {
      screens: {
        xsm: '350px',
      },
      textShadow: {
        aubergine: '1px 1px 0 #39224E',
        white: '0 0 1px #fff, 0 0 1px #fff',
        DEFAULT: '0 0 1px #000',
        bold: '0 0 1px #fff, 0 0 1px #fff',
        black: '0 1px 1px #000',
        blackSmall: '0 0 1px #000',
        whiteSmall: '0 0 1px #fff',
      },
      boxShadow: {
        custom: '0px 7px 7px 0px rgba(0, 0, 0, 0.25)',
        tooltip: '0px 1px 5px 4px rgba(0, 0, 0, 0.1)',
        overlay: '0px 10px 11px 0px rgba(0, 0, 0, 0.25)',
      },
      backgroundImage: {
        'stylized-logo': `url(${publicUrl}/stylizedLogo.svg)`,
        search: `url(${publicUrl}/search.svg)`,
      },
      gridTemplateColumns: {
        searchResultsCard: 'min-content auto',
        iconText: '20px auto',
      },
      spacing: {
        26: '26px',
        87: '87px',
        27: '27px',
      },
      colors: {
        trueBlack: '#000000',
        white: '#ffffff',
        red: '#ed1c24',
        darkGrey: '#978F85',
        mediumGrey: '#CCCBBC',
        extraLightGrey: '#EFF0ED',
        aubergine: '#39224E',
        maroon: '#8F2457',
        black: '#231F20',
        extralightPurple: '#D7B7D7 ',
        mainPurple: '#74519A',
        darkMaroon: '#761846',
        mediumPurple: '#533A75',
        lightBlue: '#21ADE4',
        darkBlue: '#127BB9',
        skyBlue: '#127BB9',
        purple2: '#694A87',
        lightPurple: '#74519A',
        darkPurple: '#67183E',
        purple: '#74519A',
        extradarkMaroon: '#551032',
        lightGrey: '#EFF0ED',
        extradarkBlue: '#106597',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: 'calc(var(--radius) - 4px)',
        2: ['7px'],
        xxl: ['100px'],
      },
      fontFamily: {
        arial: ['Arial'],
        gowlingBliss: 'var(--gowlingBliss)',
        eloquentjf: 'var(--eloquentjf)',
      },
      fontSize: {
        11: ['11px'],
        12: ['12px'],
        13.1: ['13px'],
        15.1: ['15px'],
        14.1: ['14px'],
        32: ['32px'],
        '4xl': '2rem',
      },
      margin: {
        1.5: ['6px'],
        3: ['11px'],
        3.2: ['13px'],
        4.5: ['18px'],
        4.7: ['19px'],
        5.5: ['22px'],
        7: ['27px'],
        7.2: ['29px'],
        7.5: ['30px'],
        9: ['37px'],
        10.5: ['42px'],
        11.1: ['45px'],
      },
      padding: {
        10: ['10px'],
        20: ['20px'],
        6.5: ['26px'],
        7.75: ['31px'],
        8.5: ['34px'],
        21.5: ['90px'],
        9.75: ['39px'],
      },
      width: {
        40: ['155px'],
        72: ['300px'],
        96: ['379px'],
      },
      borderWidth: {
        sm: '1px',
      },
      lineHeight: {
        normal: 'normal',
        6.75: ['27px'],
      },
      gridColumn: {
        'span-13': 'span 13 / span 13',
        'span-14': 'span 14 / span 14',
        'span-15': 'span 15 / span 15',
        'span-16': 'span 16 / span 16',
      },
      gridColumnEnd: {
        14: '14',
        15: '15',
        16: '16',
        17: '17',
      },
      gridColumnStart: {
        14: '14',
        15: '15',
        16: '16',
        17: '17',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    plugin(function ({ matchUtilities, theme }) {
      matchUtilities(
        {
          'text-shadow': (value) => ({
            textShadow: value,
          }),
        },
        { values: theme('textShadow') }
      );
    }),
  ],
  corePlugins: {
    backdropOpacity: false,
    backgroundOpacity: false,
    borderOpacity: false,
    divideOpacity: false,
    ringOpacity: false,
    textOpacity: false,
  },
};
