---
ID: "8cbec6ee-bb99-4286-aec4-c9ac8b014036"
Parent: "7d2bf142-d739-4a11-b424-4516f2ef014b"
Template: "7d2bf142-d739-4a11-b424-4516f2ef014b"
Path: /sitecore/templates/Project/GowlingWLG Site/Header/HeaderNavigation/Sub Navigation Root/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{AFF2C22E-7D16-41F6-A1D1-4C5DC844930A}"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230522T215652Z
    - ID: "30331858-c7e3-4a74-a313-f055f622fdce"
      Hint: SubNavigationTitle
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\harender.kumar@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\harender.kumar@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5bb431d7-67dc-4248-b52d-4e5cb8f439b8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\navya.mallepalli@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230705T103251Z
