---
ID: "2f9c2df1-7312-4ec6-96dd-c4b3633d2dd5"
Parent: "91c48e49-24a4-445c-baee-aded5ce2371e"
Template: "91c48e49-24a4-445c-baee-aded5ce2371e"
Path: /sitecore/templates/Project/GowlingWLG Site/Page Content/CTA Tiles/RenderingParameters/CTATileRenderingParameter/__Standard Values
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230728T105341Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\navya.mallepalli@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\navya.mallepalli@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "399f1423-808f-4c04-b608-5b1143007124"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\navya.mallepalli@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230728T105354Z
