---
ID: "49a497cd-4bfe-4b21-8c54-e12c934ad3e2"
Parent: "2cb0b8bb-78a9-4a84-ac3d-2f52b4373f04"
Template: "2cb0b8bb-78a9-4a84-ac3d-2f52b4373f04"
Path: /sitecore/templates/Project/GowlingWLG Site/Page Content/Common/Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230906T230129Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mahesh.kambhampati@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mahesh.kambhampati@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "65dfe4da-45d7-40fb-99d6-817f73c2f062"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mahesh.kambhampati@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230906T230129Z
