---
ID: "e334f407-b6af-4f25-85eb-95c3aeb3e148"
Parent: "df3f6ad0-2b6f-474d-a688-dc56dde9b1f7"
Template: "ca295d2d-fc88-4564-af21-cc1fe4cdfd6d"
Path: /sitecore/content/GowlingWLG/GowlingWLG/Home/QA/Services
SharedFields:
- ID: "4a749557-242b-4372-8a20-b2db9d406301"
  Hint: __AutoThumbnails
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1200
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230627T124419Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\navya.mallepalli@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\navya.mallepalli@altudo.co
    - ID: "77681060-f4b9-4504-b4e8-bf6e11d33601"
      Hint: Title
      Value: Services
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b9cf1695-54ce-4eec-98b8-3bfc7e7f7c1f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanjeevi.ram@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230821T123616Z
